# Generated by Django 4.0.1 on 2022-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_reservation_customer_alter_reservation_hotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
