# Generated by Django 4.0.1 on 2022-02-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_alter_imagemodel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
