# Generated by Django 4.0.1 on 2022-02-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0009_alter_hotel_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_method',
            field=models.CharField(choices=[('online_pay', 'Online Pay'), ('offline_pay', 'Offline Pay')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
