# Generated by Django 4.0.1 on 2022-02-26 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_reservation_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
