# Generated by Django 4.0.1 on 2022-02-26 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0011_reservation_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reserved_data',
            new_name='reserved_date',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
