# Generated by Django 4.0.1 on 2022-02-27 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0013_reservation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='status',
            new_name='checkin_status',
        ),
    ]
