# Generated by Django 4.0.1 on 2022-03-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0014_rename_status_reservation_checkin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_status',
            field=models.CharField(choices=[('reserved', 'reserved'), ('checked_in', 'checked_in'), ('checked_out', 'checked_out')], default='reserved', max_length=15),
        ),
    ]
