# Generated by Django 4.0.1 on 2022-03-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
